repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: fix-byte-order-marker
      - id: detect-private-key
      - id: mixed-line-ending
  - repo: https://github.com/dnephin/pre-commit-golang
    rev: v0.5.1
    hooks:
      - id: go-fmt
      - id: go-imports
      - id: go-lint
      - id: go-build
      - id: go-mod-tidy
      - id: go-critic
      - id: no-go-testing
      - id: golangci-lint
      - id: go-unit-tests
