language: go

go:
  - master

branches:
  only:
    - master
    - /^v[1-9][0.9]*\.[0-9]+\.[0-9]+(-[a-zA-Z][a-zA-Z]*)?$/

gobuild_args: -x -ldflags "-X cmd.versionString ${TRAVIS_TAG:-v0.0.0}"

script:
  - echo "Package binary"
  - echo "Deploy binary"
