package constants

var CmdKpm = "kpm"
var CmdVersion = "version"
var CmdList = "list"
var CmdRemove = "remove"
var CmdPurge = "purge"
var CmdPack = "pack"
var CmdUnpack = "unpack"
var CmdInspect = "inspect"
var CmdRun = "run"
var CmdNewPackage = "new-package"
var CmdRepo = "repositories"
var CmdRepoList = "list"
var CmdRepoFind = "find"
var CmdRepoPush = "push"
var CmdRepoPull = "pull"
